### ISSUE TITLE
What do you mean "using"?

### ISSUE THREAD

**Issue by elimisteve** [lukevers/slack-storage#1]
Like which chat application? OS? browser?

**Comment by lukevers** [comment]
I updated the README to explain this more a bit. This is an API to interface with [Slack](https://slack.com/) as a "Slash Command."

**Comment by lukevers** [comment]
To add some more information, once you setup a "Slash Command" (I'll add docs later when it's more stable) you can use it within slack. Here's an example of what happens if you run `/using` (or whatever you set it to! Slack lets you pick the name)

![screen shot 2016-02-16 at 7 08 44 pm](https://cloud.githubusercontent.com/assets/1558388/13095585/c5d56eb8-d4e0-11e5-9f3b-1a19e0ccca0f.png)

You can basically use this for a string-storage within Slack. You could name the command `save` if you wanted to.

```
/save key value can be a lot of characters
```
